name: Sync Python lab to playground-lab

on:
  push:
    paths:
      - 'lab/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v3

      - name: Push para o repositório playground-lab
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'lab'
          destination-github-username: 'emellybmuniz'
          destination-repository-name: 'playground-lab'
          target-branch: 'main'
          target-directory: 'python'
          user-email: emellybmuniz@gmail.com
          user-name: emellybmuniz
          commit-message: "feat(python): sync lab updates from python-playground"